services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bytebankdb

  api:
    image: brendhon/bytebank-api-graphql:latest
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bytebankdb
      - NODE_ENV=development
      - JWT_SECRET=bytebank-pro-jwt-secret-2025
      - PORT=3000
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
